### ISSUE TITLE
The app will not run in any AMD machine it lunch but it won't run properly , bad result for good pack.

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ex0days#1]
Hello , the app runs good in Windows 10 64 bit on an INTEL laptop  , but it wont run on the same OS on other AMD machines , 

I tried different machines it won't work in AMD , friends also reported this to me i didnt know why the app wasn't working because it runs perfect on with INTEL , 

it won't run properly , it does start , it does open the GUI but run as in giving result it doen't , it keep shows error even if the zips are dont have any errors , always shown this error and it dont extract all zips just one zip even there is many zips are exist 

KO (error #2 on zip file:  this is the error that will be shown in every folder . 

hope this can be fixed , thank you.

**Comment by mbruel** [comment]
Hi,
Well if the app opens, it means the issue doesn't come from the app itself but from the compression tool.
Try to install 7zip on an AMD and change the path of 7zip to point on it. (7z.exe)
Maybe you can try using Winrar instead, I suppose it supports zip format. You can make it point on WinRar.exe (instead of 7z.exe). But 7z is the one used by default and I believe it supports much more format than WinRar. But if you only have zip, ace, arj and rar, go for WinRar if you want.

It is normal that it doesn't extract all zip files. If one is corrupted (or if there is an error) we jump directly to the next folder as we'll miss files for the second decompression...

**Comment by DEVUVO** [comment]
hmm that make a different , the app requires a 7Z to be installed in the OS , if the 7z NOT installed the error will stay logged

after i installed the 7z the app will work in windows 10 with AMD cpu no problem

this is done for now , thank you

**Comment by mbruel** [comment]
It sounds 7z.exe needs one dll: IEShims.dll
I'm going to include it on the next release. That should fix the issue.
Can you try? Here is the dll: https://files.fm/u/dpjjwuc9
Just add it in the folder of ex0days.
7zip shouldn't need to be installed then.
And hopefully it should work on both intel and amd ;)
